### ISSUE TITLE
支持libev客户端吗？

### ISSUE THREAD

**Issue by qiuzi** [Lupino/shadowsocks-auth#1]
客户端要求是什么？
服务端支持单端口多用户的管理吗？

**Comment by Lupino** [comment]
在原来的数据包上面加上用户名:      \x01 + 用户名的长度 +  用户名 + 原来的数据包

不会 C 的开发, 所以没有 C 的客户端

**Comment by Lupino** [comment]
用户管理是通过修改 redis 里面的数据来实现的部分代码参考 
https://gist.github.com/Lupino/d0609ab79d873b2c1015

**Comment by qiuzi** [comment]
支持c的libev客户端吗？

**Comment by Lupino** [comment]
不知支持， 你可以根据协议修改一下 libev 客户端
