### ISSUE TITLE
对大文件的支持？

### ISSUE THREAD

**Issue by lairdnote** [Lupino/shadowsocks-auth#11]
我测试了一下发现下载大文件的时候不完整。
请问是buf 调整的太小了吗？
`{ [data not shown]
- transfer closed with 263894548 bytes remaining to read`
  curl 结果

server 端信息：

`GET http://distfiles.gentoo.org/releases/x86/autobuilds/current-stage3-i686/install-x86-minimal-20160802.iso "curl/7.35.0" HTTP/1.1 200 lupino 3492752`

**Comment by zyfdegh** [comment]
@lairdnote Due to closed TCP connection, I guess.
