### ISSUE TITLE
make wth errors

### ISSUE THREAD

**Issue by vvx1024** [Lupino/shadowsocks-auth#13]
cd server;go get -v -d; go build -o /bin/server
cd local;go get -v -d; go build -o /bin/local
# _/root/shadowsocks-auth/local
./local.go:360:24: not enough arguments in call to shadowsocks.PipeThenClose
	have (net.Conn, *shadowsocks.Conn)
	want (net.Conn, net.Conn, func(int))
./local.go:361:21: not enough arguments in call to shadowsocks.PipeThenClose
	have (*shadowsocks.Conn, net.Conn)
	want (net.Conn, net.Conn, func(int))
make: *** [all] Error 2

## what is the version of go? 
go 需要哪个版本？我使用yum install go安装的

**Comment by Lupino** [comment]
fixed. compile error on https://github.com/Lupino/shadowsocks-auth/commit/4375a6df21c6e64bc042950358f94875292261b9
