### ISSUE TITLE
version not supported

### ISSUE THREAD

**Issue by zshtom** [Lupino/shadowsocks-auth#9]
求助下作者 两个问题
1、用哪个版本的go 编译比较合适
2、运行后 有这个报错
2015/12/29 09:41:06 Error get passeoed: 8388 version %!s(uint8=165) not supported

然后 chrome 报错 ERR_CONNECTION_CLOSED ，请问是什么原因

**Comment by Lupino** [comment]
1、go 版本没有限制
2、运行后报错： 客户端的版本不一样或者使用了不兼容的客户端

**Comment by zshtom** [comment]
了解了，多谢！

在 2016-01-22 10:45:36，"lupino" notifications@github.com 写道：

1、go 版本没有限制
2、运行后报错： 客户端的版本不一样或者使用了不兼容的客户端
